name: aws-s3-lock
description: Wait on, acquire, and clean-up S3-based locks
author: "Freckle"
inputs:
  name:
    description: "Name for the lock"
    required: true
  s3-bucket:
    description: "Name of existing S3 bucket to use. If empty, one will be created."
    required: true
  s3-prefix:
    description: "Prefix for lock files within s3-bucket"
    required: false
    default: ""
  expires:
    description: |
      How long to aquire the lock for. Default is 15m.
    required: true
    default: 15m
  timeout:
    description: |
      How long to wait for the lock to become available. Default matches
      expires.
    required: false
  timeout-poll:
    description: |
      How long to wait between checks for the lock. Default is 5s.
    required: true
    default: 5s

outputs:
  acquired-at:
    description: "Timestamp of acquisition, or null"
  released-at:
    description: "Timestamp of release, or null"

runs:
  using: "node20"
  main: "dist/acquire/index.js"
  post: "dist/release/index.js"
